FROM rust:1.93-slim-bookworm AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/var/cache/cargo \
    CARGO_HOME=/var/cache/cargo cargo build

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/target/release/server ./server
COPY migrations ./migrations
COPY config.container.yaml ./config.yaml

ENV CONFIG_PATH=/app/config.yaml
EXPOSE 8080
VOLUME ["/data"]

CMD ["./server"]
